[build]
  command = "npm run build"
  publish = "dist"  # Change this to "build" if using Create React App or similar

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200